export const VALIDATE_CART_ITEMS_REQUEST = 'cart/VALIDATE_CART_ITEMS_REQUEST';
export const VALIDATE_CART_ITEMS_SUCCESS = 'cart/VALIDATE_CART_ITEMS_SUCCESS';
export const VALIDATE_CART_ITEMS_FAILURE = 'cart/VALIDATE_CART_ITEMS_FAILURE';
