// Fetch
export const FETCH_ADDRESS_REQUEST = 'FETCH_ADDRESS_REQUEST';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAILURE = 'FETCH_ADDRESS_FAILURE';
export const CLEAR_ADDRESSES       = 'CLEAR_ADDRESSES';

// Save (Add)
export const SAVE_ADDRESS_REQUEST = 'SAVE_ADDRESS_REQUEST';
export const SAVE_ADDRESS_SUCCESS = 'SAVE_ADDRESS_SUCCESS';
export const SAVE_ADDRESS_FAILURE = 'SAVE_ADDRESS_FAILURE';

// Update (Edit)
export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAILURE = 'UPDATE_ADDRESS_FAILURE';

// Delete
export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE';

// Delivery Quote
export const DELIVERY_QUOTE_REQUEST = 'DELIVERY_QUOTE_REQUEST';
export const DELIVERY_QUOTE_SUCCESS = 'DELIVERY_QUOTE_SUCCESS';
export const DELIVERY_QUOTE_FAILURE = 'DELIVERY_QUOTE_FAILURE';
export const CLEAR_DELIVERY_QUOTE   = 'CLEAR_DELIVERY_QUOTE';

// Selected address for current checkout flow
export const SET_SELECTED_ADDRESS_ID = 'SET_SELECTED_ADDRESS_ID';
